test-plan:
  path: "./TestPlans/S01_SimpleExample/Test_get_properties.jmx"
  properties:
    - name: "prop1"
      value: "value1"
    - name: "prop2"
      value: "value2"
  results:
    output-file: "result.jtl"
  report:
    output-directory: "./reports/html/"
    generate: true

jmeter:
  additional-args: "-Djava.awt.headless=true"
  url: "http://example.com"
  concurrency: 10
  hold-for: "1m"
  ramp-up: "1m"
