on: [push]
jobs:
  jmeter_job:
    runs-on: ubuntu-latest
    name: JMeter Test Execution
    steps:      
    - name: Checkout
      uses: actions/checkout@v4

    - name: Create reports directory
      run: mkdir reports
      
    - name: Run JMeter Tests
      uses: ./
      with:
        config-path: ./TestPlans/config.yml
        args: "-e -o ./reports/html/"
        
    - name: Upload Results
      uses: actions/upload-artifact@v4.3.3
      with:
        name: jmeter-results
        path: result.jtl
        if-no-files-found: error

    - name: Upload HTML Reports
      uses: actions/upload-artifact@v4.3.3
      with:
        name: jmeter-reports
        path: reports
        if-no-files-found: error
