name: PerfAction Test

on:
  push:
    branches:
      - main  # adjust as needed

jobs:
  performance-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install dependencies
        run: sudo apt-get install -y build-essential git

      - name: Clone PerfAction repository
        run: git clone https://github.com/example/perfaction.git /tmp/perfaction

      - name: Build PerfAction
        run: |
          cd /tmp/perfaction
          ./build.sh  # or the relevant build command

      - name: Move PerfAction binary
        run: sudo mv /tmp/perfaction/bin/perfaction /usr/local/bin/perfaction

      - name: Run PerfAction
        run: |
          perfaction run --config config/perfaction-config.yml
