name: PerfAction Test

on:
  push:
    branches:
      - main  # adjust as needed

jobs:
  performance-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Java
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '11'

      - name: Run PerfAction
        run: |
          perfaction run --config config/perfaction-config.yml
